### ISSUE TITLE
Separating logic & achieving long term maintainability

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/giveth-bot#10]
Glancing at the code, I would suggest that you already split the bot in at least 3 separate files:

- Configuration
- Pointsbot
- Chatbot

Otherwise this will become unmaintainable quickly.

**Comment by Quazia** [comment]
I agree with this, I would even suggest separating out the input/output logic and the generative logic?

**Comment by deamme** [comment]
Fixed by https://github.com/Giveth/giveth-bot/pull/14
