### ISSUE TITLE
too many welcomes

### ISSUE THREAD

**Issue by loietaylor** [Giveth/giveth-bot#27]
We're getting spammed by the Giveth Bot! Probably not necessary to welcome someone every time they change something about their account (display name, prof pic, etc) 
<img width="363" alt="screen shot 2018-10-05 at 3 28 07 pm" src="https://user-images.githubusercontent.com/38163206/46538178-91770e00-c8b3-11e8-99e9-f35c61db50a9.png">
<img width="351" alt="screen shot 2018-10-05 at 3 28 23 pm" src="https://user-images.githubusercontent.com/38163206/46538184-93d96800-c8b3-11e8-81a3-fce93e830c50.png">

**Comment by FrederikBolding** [comment]
Yep - thats definitely a bug. Looking at it now 😄

**Comment by FrederikBolding** [comment]
@lorelei1 Thanks for reporting - should be fixed when #29 is merged 😄
