### ISSUE TITLE
Add a way to dish the same amount of points to multiple users in one message

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-bot#32]
Can we make the input for the handles able to accept multiple inputs? So the format changes from 

!dish [#of points] [type of points] points to [handle] for [reason]
to
!dish [#of points] [type of points] points to [handle, handle, handle] for [reason]

So instead of going: 
!dish 10 gov points to @geleeroyale:matrix.org for going to both the comms and gov meetings this week
!dish 10 gov points to @krrisis:matrix.org for going to both the comms and gov meetings this week
!dish 10 gov points to @loie:matrix.org for going to both the comms and gov meetings this week
!dish 10 gov points to @r33pich33p:matrix.org for going to both the comms and gov meetings this week

I would just do 

!dish 10 gov points to @geleeroyale:matrix.org, @krrisis:matrix.org, @loie:matrix.org, @r33pich33p:matrix.org for going to both the comms and gov meetings this week

**Comment by FrederikBolding** [comment]
That should definitely be possible 😄
