### ISSUE TITLE
Change The PR Approval Process

### ISSUE THREAD

**Issue by YalorMewn** [Giveth/giveth-bot#38]
Currently we have to get ahold of a single person to get each PR merged, since this is a community tool we would like to have the access the updating and approval process also be achievable by members of the community. 

One discussion was for PR's to be approved via a gmail address. Not sure the options here, but happy to work with what is possible to get this updated. 

Feel free to ask clarifying questions in the comments. Or head to social coding to clarify https://riot.im/app/#/room/#giveth-social-coding:matrix.org and ping @bowensanders if you have any questions.

**Comment by krrisis** [comment]
You were already able to merge, and so were frederik & deam. Now we added @bowensanders , but there's also Kay & I (or even vojtech or griff etc) so that's a bunch. If there's someone specific that needs to be added, just shout. So no need for a bounty.

**Comment by YalorMewn** [comment]
Interesting, no one told me :)
