### ISSUE TITLE
bot for scheduled messages

### ISSUE THREAD

**Issue by loietaylor** [Giveth/giveth-bot#42]
Would be great to have a little tool allowing us to schedule a message to be sent at a certain time! 
Uses:
- recurring messages in rooms (I would definitely put this to use in the Unicorn DAC room)
- delaying a reminder to someone in a private chat to make sure they see the reminder of their task at the relevant moment

Could be initiated by a simple command to the bot like "!schedule message to be delivered at 10 am January 25th" that would precede the message text. I imagine we'd want clear parameters of which messages are delayed and which are not, so either a hard rule that only the text within the same box as the command to the bot, or making something like the text to be sent at later date is in between < these things > or somethin. 

Would the others in the room (the recipients) see that something has been scheduled, or would it show no trace on their end until the scheduled time arrives? If invisible to them until that point, would it also be invisible to me (the sender)? Ideally theres a record that the sender can see but the recipients can't, until the time arrives to send. But those are unnecessary ideals of elegance ;)

**Comment by loietaylor** [comment]
@FrederikBolding

**Comment by krrisis** [comment]
This would be nice but observing how riot works I'd say, yeah, people would see you schedule this, which is okay I think if it's something for larger rooms or for regularly recurring messages?  

What would you think of a command like 
!schedule [message text] [hour] [date] [recurring weekly y/n] 
... with the [weekly recurring] part of the command saying if it keeps sending it every week on that hour & day of the week? 
... and where you'll also have to decide on an hour and date format bcs we're all in different timezones :) (UTC or CEST I'd say)

And then you'll need a 'stop that scheduled message' command too, something like 
!stopschedule [message text]
... where the bot listens if you copy the exact text (in that sense it doesn't stop all yr scheduled messages) 
... and where we have to decide if the bot only listens to the person who started that scheduled message or to anyone

Just some ideas to make it more tangible & workable for frederik or anyone else who wants to pick it up

**Comment by FrederikBolding** [comment]
Thanks for the input @krrisis ! The current pull request just defines the messages as all other messages in the constants.js

I think for an initial version it's the simplest way to do it. Also doesn't cause as much confusion as doing commands.

**Comment by krrisis** [comment]
that's an even simpler solution for now, as I don't think we'll be using it that much anyways. thx frederik!
