### ISSUE TITLE
Add a new command !cal or !calendar

### ISSUE THREAD

**Issue by bowensanders** [Giveth/giveth-bot#43]
I'd like to add a command - !cal or !calendar - that responds with a short list of upcoming meetings and hackathons and similar things of upcoming use to the denizens of #socialcoding (and other channels, but I would likely be the one to curate the calendar entries.

**Comment by FrederikBolding** [comment]
@bowensanders Great idea! Would you base it on just a variable that you set manually here in GitHub or an actual calendar that we load x amount of next events from?

**Comment by geleeroyale** [comment]
Wow - next events would be awesome! You could include a link to the full calendar in the bot message:

http://calendar.giveth.io (for a secure link, we could use the share link, but it does not look as clean)

**Comment by FrederikBolding** [comment]
@geleeroyale We could probably pull events from that public calendar if needed?

**Comment by bowensanders** [comment]
Well, we could have it poll a changeable resource off the web or change things in the static answer. As for polling the calendar, I don't know how easy it would be to flag the things from the google calendar I care about to put in the channel bot (i only want a specific set of things) so we'd have to figure that out

**Comment by FrederikBolding** [comment]
@bowensanders It's really up to you, just give me a resource that is somewhat easy to pull from. You could do a custom calendar, that way we can add both functions? You decide!

**Comment by FrederikBolding** [comment]
After discussing with @bowensanders - We've decided to split it into two features: A main calendar, which shows the next Hackathons (this issue, which will be implemented first), and another feature with more specialized calendar entries, such as meeting times (#44).
