### ISSUE TITLE
Amin's points not showing up in RewardDAO tally sheets

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-bot#57]
See this dish:  https://riot.im/app/#/room/#giveth-product-development:matrix.org/$155912159114216IxtrL:matrix.org

I can't find it on the RewardDAO Now or Monthly spreadsheets..  perhaps it's because his handle is :privacytools.io instead of :matrix.org   ??

**Comment by FrederikBolding** [comment]
Hmm, weird. As he has been dished points successfully before. https://docs.google.com/spreadsheets/d/12cblUYuYq4NwZX7JdRo0-NWnrOxlDy-XCbvF3ugzb2c/edit#gid=0&range=A407

**Comment by Danibelle** [comment]
Yes - there are several strange things goin on here..

First is the 25 points dished by Griff that don't show at all, in RewardDAO or in the Points Import for May:
https://docs.google.com/spreadsheets/d/1TtXytm-QkaPwUhHjlCoYQ4S3DIm9KFHaJk0ON_RjNmg/edit#gid=1240912228

Additionally, even though the 50 points I dished show up in the Import tab, Amin AND a second recipient, Hutch, didn't show up at all in the Results tab (we manually added them to allocate their ETH in the scoring meeting.

These seem to be separate issues; one in the RewardDAO Now spreadsheet calculations and a second, different one in the May calculation spreadsheet.

**Comment by FrederikBolding** [comment]
I'm merging in #60 now, which should prevent rows from being overwritten. This might fix the problem, but I can't be sure, as I haven't found evidence that the issue is caused by overwriting.

**Comment by FrederikBolding** [comment]
Moved discussion to #64 as is better titled.
