### ISSUE TITLE
Some rewardDAO points not appearing in spreadsheet

### ISSUE THREAD

**Issue by gentlemandonadams** [Giveth/giveth-bot#64]
Kris dished some COMMS points in the contributors room that did not make it into the spreadsheet for some reason.  

https://matrix.to/#/!OQTaDMKEJXLvTpYoCe:matrix.org/$1560958398279011CMTVt:matrix.org?via=matrix.org&via=giveth.io&via=privacytools.io
https://matrix.to/#/!OQTaDMKEJXLvTpYoCe:matrix.org/$1560958324278750cFPJm:matrix.org?via=matrix.org&via=giveth.io&via=privacytools.io

**Comment by FrederikBolding** [comment]
This dish: https://riot.im/app/#/room/#giveth-product-development:matrix.org/$155912159114216IxtrL:matrix.org (as per #57 ) had problems too.

Will look into this again.
